### ISSUE TITLE
Invalid name. Please only use valid python identifiers

### ISSUE THREAD

**Issue by oleksandr** [python-medikit/medikit#107] opened 2018-11-30 07:52 UTC
Using OSX and Python 3.7.1 with Pipenv, I try to initialize the project according to Getting started:

```
$ medikit init sample
  ✚  Medikit v.0.6.3-6-ge9bb127 (git)  ✚
Name: sample
ERR.:0002:root: Invalid name. Please only use valid python identifiers.
```
Anyone knows what's going wrong here?

**Comment by hartym** [comment] 2019-03-20 07:17
There seems to be a bug there, that I reproduced once but not anymore on master.

Next version will use `os.path.basename(target)` as a default, I don't really understand why you got this though. Feel free to investigate (code is in ProjectInitializer class).

Can you confirm that the attached patch branch fixes it for you ?

**Comment by hartym** [comment] 2019-05-29 08:36
Closing (can't reproduce).

If you still have the issue, please say.

**Closed as completed by hartym** 2019-05-29 08:36 UTC
